version: '3.8'
services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - auth/.env
    volumes:
      - ServiceDesk_test:/var/lib/postgresql/data/ # том для сохранения данных
    networks:
      - my_network_ServiceDesk
    ports:
      - "5432:5432"

volumes:
  ServiceDesk_test:
    name: "ServiceDesk_test"

networks:
  my_network_ServiceDesk:
    driver: bridge